name: CI

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # This doesn't run on the Atlas board
  codestyle:
    runs-on: ubuntu-18.04

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Set up environment
        run: bash Webservice/scripts/setup.sh --yes

      - name: Check code style
        run: bash Webservice/scripts/check_code_formatting.sh

  # This runs on the Atlas board
  test:
    runs-on: self-hosted

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Set up environment
        run: bash Webservice/scripts/setup.sh --yes

      - name: Try to import the acl library
        run: bash Webservice/scripts/check_acl_library.sh

      - name: Run unittests
        run: bash Webservice/scripts/test.sh
