name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  codestyle:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Set up environment
        run: bash Webservice/scripts/setup.sh --yes

      - name: Check code formatting
        run: |
          bash Webservice/scripts/test.sh
