name: CI

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # This doesn't run on the Atlas board
  codestyle:
    runs-on: ubuntu-18.04

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Set up Python 3.7.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.5

      - name: Set up environment
        run: bash scripts/setup.sh --yes

      - name: Check code style
        run: bash scripts/check_code_formatting.sh

  # This runs on the Atlas board
  test:
    runs-on: self-hosted

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$HOME/Ascend/ascend-toolkit/latest/pyACL/python/site-packages/acl" >> $GITHUB_ENV

      - name: Set up environment
        run: bash scripts/setup.sh --yes

      - name: Try to import the acl library
        run: bash scripts/check_acl_library.sh

      - name: Run tests
        run: bash scripts/test.sh
